//! The ISOM 2017-2 symbol table (ADR 0006): the codes the isom-maplibre style draws and
//! the table each is read from, generated by `build.rs` from the vendored copy in
//! `vendor/isom-maplibre/isom.yaml`. Refresh the copy with `scripts/sync-isom-table.sh`;
//! never edit it by hand.

use std::{fmt, str::FromStr};

include!(concat!(env!("OUT_DIR"), "/isom_table.rs"));

/// The geometry a symbol is drawn with.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SymbolGeometry {
    Point,
    Line,
    Area,
}

impl IsomCode {
    /// Every code in the table, in ascending order.
    pub fn all() -> &'static [IsomCode] {
        Self::ALL
    }
}

impl fmt::Display for IsomCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A code string the symbol table does not list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownIsomCode(pub String);

impl fmt::Display for UnknownIsomCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?} is not in the isom-maplibre symbol table", self.0)
    }
}

impl std::error::Error for UnknownIsomCode {}

impl FromStr for IsomCode {
    type Err = UnknownIsomCode;

    /// Parses an "NNN.NNN" code; plain numbers ("101") are not codes.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .iter()
            .copied()
            .find(|code| code.as_str() == s)
            .ok_or_else(|| UnknownIsomCode(s.to_string()))
    }
}

/// Written as the "NNN.NNN" string, the GeoJSON `isom_code`.
impl serde::Serialize for IsomCode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

/// Read from the "NNN.NNN" string; a code the table does not list is an error.
impl<'de> serde::Deserialize<'de> for IsomCode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        s.parse().map_err(serde::de::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_table_matches_its_schema() {
        let schema: serde_json::Value =
            serde_json::from_str(include_str!("../vendor/isom-maplibre/isom.schema.json")).unwrap();
        // isom.yaml as build.rs parsed it, anchors resolved
        let table: serde_json::Value =
            serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/isom.json"))).unwrap();
        let validator = jsonschema::validator_for(&schema).unwrap();
        let errors: Vec<String> = validator
            .iter_errors(&table)
            .map(|e| format!("{}: {e}", e.instance_path()))
            .collect();
        assert!(errors.is_empty(), "isom.yaml fails its schema: {errors:#?}");

        // and the schema bites: a plain number is not a code
        let mut broken = table;
        broken["stack"][0]["symbols"][0]["code"] = "101".into();
        assert!(!validator.is_valid(&broken));
    }

    #[test]
    fn codes_round_trip_as_nnn_nnn_strings() {
        assert!(!IsomCode::all().is_empty());
        for &code in IsomCode::all() {
            let s = code.to_string();
            assert!(
                s.len() == 7
                    && s.as_bytes()[3] == b'.'
                    && s.bytes().filter(u8::is_ascii_digit).count() == 6,
                "{s} is not NNN.NNN"
            );
            assert_eq!(s.parse::<IsomCode>(), Ok(code));
        }
        assert!(IsomCode::all().is_sorted());
        assert_eq!(
            "101".parse::<IsomCode>(),
            Err(UnknownIsomCode("101".to_string()))
        );
    }

    #[test]
    fn codes_carry_their_table_and_geometry() {
        use SymbolGeometry::*;
        let expected = [
            (IsomCode::C101_000, IsomTable::Contours, Line),
            (IsomCode::C101_001, IsomTable::Contours, Line), // slope line, line-center icon
            (IsomCode::C109_000, IsomTable::KnollsPoints, Point),
            (IsomCode::C111_000, IsomTable::KnollsPoints, Point),
            (IsomCode::C201_000, IsomTable::Cliffs, Line),
            (IsomCode::C206_000, IsomTable::Cliffs, Area),
            (IsomCode::C301_000, IsomTable::Water, Area), // fill plus bank line
            (IsomCode::C403_000, IsomTable::VegetationAreas, Area),
            (IsomCode::C502_000, IsomTable::Paths, Line), // casing plus core
            (IsomCode::C520_000, IsomTable::Manmade, Area),
            (IsomCode::C521_001, IsomTable::Manmade, Area),
        ];
        for (code, table, geometry) in expected {
            assert_eq!((code.table(), code.geometry()), (table, geometry), "{code}");
        }
        let names: Vec<&str> = IsomTable::ALL.iter().map(|t| t.as_str()).collect();
        assert_eq!(
            names,
            [
                "contours",
                "cliffs",
                "knolls_points",
                "vegetation_areas",
                "water",
                "paths",
                "manmade"
            ]
        );
    }

    /// The GeoJSON schema types each property class's `isom_code` as an enum of the codes
    /// KP emits in it: every one is in the symbol table, in the table the class is
    /// written to. Mapping file codes are held to the table when they are parsed.
    #[test]
    fn schema_codes_are_in_the_table_of_their_class() {
        let schema: serde_json::Value =
            serde_json::from_str(include_str!("../schema/geojson.schema.json")).unwrap();
        let classes = [
            ("ContourProperties", IsomTable::Contours),
            ("KnollProperties", IsomTable::KnollsPoints),
            ("CliffProperties", IsomTable::Cliffs),
            ("VegetationProperties", IsomTable::VegetationAreas),
        ];
        for (class, table) in classes {
            let codes = schema["$defs"][class]["properties"]["isom_code"]["enum"]
                .as_array()
                .unwrap_or_else(|| panic!("{class}: isom_code is not an enum"));
            assert!(!codes.is_empty());
            for code in codes {
                let code: IsomCode = code.as_str().unwrap().parse().unwrap();
                assert_eq!(code.table(), table, "{class}: {code}");
            }
        }
    }
}
