//! The ISOM 2017-2 symbol table (ADR 0006): the codes the isom-maplibre style draws and
//! the table each is read from, generated by `build.rs` from the vendored copy in
//! `vendor/isom-maplibre/isom.yaml`. Refresh the copy with `scripts/sync-isom-table.sh`;
//! never edit it by hand.

use std::{fmt, str::FromStr};

include!(concat!(env!("OUT_DIR"), "/isom_table.rs"));

/// The geometry a symbol is drawn with.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Geometry {
    Point,
    Line,
    Area,
}

impl IsomCode {
    /// Every code in the table, in ascending order.
    pub fn all() -> &'static [IsomCode] {
        Self::ALL
    }
}

impl fmt::Display for IsomCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A code string the symbol table does not list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownIsomCode(pub String);

impl fmt::Display for UnknownIsomCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?} is not in the isom-maplibre symbol table", self.0)
    }
}

impl std::error::Error for UnknownIsomCode {}

impl FromStr for IsomCode {
    type Err = UnknownIsomCode;

    /// Parses an "NNN.NNN" code; plain numbers ("101") are not codes.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .iter()
            .copied()
            .find(|code| code.as_str() == s)
            .ok_or_else(|| UnknownIsomCode(s.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geometry::Classification;

    #[test]
    fn vendored_table_matches_its_schema() {
        let schema: serde_json::Value =
            serde_json::from_str(include_str!("../vendor/isom-maplibre/isom.schema.json")).unwrap();
        // isom.yaml as build.rs parsed it, anchors resolved
        let table: serde_json::Value =
            serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/isom.json"))).unwrap();
        let validator = jsonschema::validator_for(&schema).unwrap();
        let errors: Vec<String> = validator
            .iter_errors(&table)
            .map(|e| format!("{}: {e}", e.instance_path()))
            .collect();
        assert!(errors.is_empty(), "isom.yaml fails its schema: {errors:#?}");

        // and the schema bites: a plain number is not a code
        let mut broken = table;
        broken["stack"][0]["symbols"][0]["code"] = "101".into();
        assert!(!validator.is_valid(&broken));
    }

    #[test]
    fn codes_round_trip_as_nnn_nnn_strings() {
        assert!(!IsomCode::all().is_empty());
        for &code in IsomCode::all() {
            let s = code.to_string();
            assert!(
                s.len() == 7
                    && s.as_bytes()[3] == b'.'
                    && s.bytes().filter(u8::is_ascii_digit).count() == 6,
                "{s} is not NNN.NNN"
            );
            assert_eq!(s.parse::<IsomCode>(), Ok(code));
        }
        assert!(IsomCode::all().is_sorted());
        assert_eq!(
            "101".parse::<IsomCode>(),
            Err(UnknownIsomCode("101".to_string()))
        );
    }

    #[test]
    fn codes_carry_their_table_and_geometry() {
        use Geometry::*;
        let expected = [
            (IsomCode::C101_000, IsomTable::Contours, Line),
            (IsomCode::C101_001, IsomTable::Contours, Line), // slope line, line-center icon
            (IsomCode::C109_000, IsomTable::KnollsPoints, Point),
            (IsomCode::C111_000, IsomTable::KnollsPoints, Point),
            (IsomCode::C201_000, IsomTable::Cliffs, Line),
            (IsomCode::C206_000, IsomTable::Cliffs, Area),
            (IsomCode::C301_000, IsomTable::Water, Area), // fill plus bank line
            (IsomCode::C403_000, IsomTable::VegetationAreas, Area),
            (IsomCode::C502_000, IsomTable::Paths, Line), // casing plus core
            (IsomCode::C520_000, IsomTable::Manmade, Area),
            (IsomCode::C521_001, IsomTable::Manmade, Area),
        ];
        for (code, table, geometry) in expected {
            assert_eq!((code.table(), code.geometry()), (table, geometry), "{code}");
        }
        let names: Vec<&str> = IsomTable::ALL.iter().map(|t| t.as_str()).collect();
        assert_eq!(
            names,
            [
                "contours",
                "cliffs",
                "knolls_points",
                "vegetation_areas",
                "water",
                "paths",
                "manmade"
            ]
        );
    }

    /// Every plain symbol number KP emits today, from [`Classification::symbol_code`] and
    /// the bundled vector mapping files, held against the table. The known gap is spelled
    /// out so the switch to `isom_code` (ENG-310) has to settle it.
    #[test]
    fn codes_kp_emits_today_are_in_the_table_but_518() {
        use Classification::*;
        let classifications = [
            ContourSimple,
            Contour,
            ContourIndex,
            ContourIntermed,
            ContourIndexIntermed,
            Depression,
            DepressionIndex,
            DepressionIntermed,
            DepressionIndexIntermed,
            Formline,
            FormlineDepression,
            Dotknoll,
            Udepression,
            UglyDotknoll,
            UglyUdepression,
            Knoll1010,
            Cliff2,
            Cliff3,
            Cliff4,
            SlopeLine,
            SmallDepression,
            Veg403,
            Veg406,
            Veg407,
            Veg408,
            Veg410,
        ];
        let mut emitted: Vec<String> = classifications
            .iter()
            .filter_map(Classification::symbol_code)
            .map(str::to_string)
            .collect();
        for mapping in [
            include_str!("../osm.txt"),
            include_str!("../fastighetskartan.txt"),
        ] {
            emitted.extend(mapping.lines().filter_map(|line| {
                let code = line.split('|').nth(1)?.trim();
                Some(code.strip_suffix('T').unwrap_or(code).to_string())
            }));
        }
        emitted.sort();
        emitted.dedup();

        let missing: Vec<&str> = emitted
            .iter()
            .filter(|code| format!("{code}.000").parse::<IsomCode>().is_err())
            .map(String::as_str)
            .collect();
        // 518 (impassable fence or wall, osm.txt `barrier`) has no symbol in isom-maplibre
        assert_eq!(missing, ["518"], "emitted: {emitted:?}");
    }
}
